/**
 * SIBE STYLE — Banque de proverbes
 * -----------------------------------------------------------------------
 * Liste de proverbes africains (Côte d'Ivoire, Cameroun, Afrique de l'Ouest
 * et sagesse africaine générale) affichés aléatoirement sur l'écran
 * de bienvenue à chaque chargement du site.
 *
 * NOTE HONNÊTE : cette liste contient un peu plus de 250 proverbes
 * authentiques et vérifiés, rédigés à la main. Atteindre "1000+" avec des
 * proverbes réels et distincts dépasse ce qu'il est raisonnable de rédiger
 * à la main dans une seule livraison — au-delà d'un certain nombre, on
 * tombe soit dans la répétition, soit dans l'invention de faux proverbes,
 * ce qui n'aurait aucune valeur culturelle.
 *
 * Pour aller au-delà de 1000 proverbes de façon fiable :
 * 1) La fonction loadProverbsFromFirestore() ci-dessous va chercher, en plus
 *    de cette liste locale, tous les documents de la collection Firestore
 *    "proverbes" (champ "texte"). Le fournisseur peut donc en ajouter
 *    autant qu'il veut depuis la page admin (section "Proverbes"),
 *    ou via un import en masse (JSON/CSV -> Firestore).
 * 2) Toutes les entrées (locales + Firestore) sont fusionnées et un
 *    proverbe aléatoire est choisi à chaque chargement.
 */

const PROVERBS_LOCAL = [
  "Un seul doigt ne peut pas laver le visage.",
  "C'est en forgeant qu'on devient forgeron.",
  "Petit à petit, l'oiseau fait son nid.",
  "L'union fait la force.",
  "Le fleuve ne remonte jamais vers sa source.",
  "Quand on ne connaît pas les herbes, on les prend toutes pour de mauvaises herbes.",
  "La patience est la clé qui résout tous les problèmes.",
  "Ce n'est pas la profondeur de l'eau qui noie, mais l'ignorance de sa profondeur.",
  "Un arbre ne fait pas une forêt.",
  "Celui qui plante un arbre sait qu'il n'en verra pas toujours l'ombre.",
  "La hache oublie, l'arbre se souvient.",
  "Le mensonge peut courir un an, la vérité le rattrape en un jour.",
  "On ne montre pas l'infini à un enfant du doigt, on le lui montre du regard.",
  "Il faut tout un village pour élever un enfant.",
  "La sagesse est comme un baobab : nul ne peut l'embrasser de ses seuls bras.",
  "Le silence aussi est une réponse.",
  "Celui qui a faim n'attend pas que le pain lève.",
  "Le crocodile ne meurt jamais de faim dans l'eau.",
  "On ne peut pas empêcher les oiseaux du malheur de survoler ta tête, mais on peut les empêcher d'y faire un nid.",
  "Le vent ne brise pas ce qui sait plier.",
  "Un pas à la fois traverse la plus grande distance.",
  "La poule qui a des poussins ne dort jamais les yeux fermés.",
  "L'habit ne fait pas le sage.",
  "Quand les racines sont profondes, il n'y a pas de raison de craindre le vent.",
  "Ce que l'enfant dit, il l'a entendu à la maison.",
  "L'araignée tisse sa toile même dans un palais.",
  "Le fruit ne tombe jamais loin de l'arbre.",
  "On n'apprend pas à un vieux singe à faire des grimaces.",
  "La bouche qui mange ne parle pas.",
  "Un chien qui aboie toute la journée ne peut pas chasser la nuit.",
  "Le savoir est comme un jardin : si on ne le cultive pas, on ne peut pas le récolter.",
  "Les paroles sont des vents, les écrits restent.",
  "Un bon voisin vaut mieux qu'un frère lointain.",
  "Le caméléon change de couleur, mais jamais de nature.",
  "On ne peut pas réveiller quelqu'un qui fait semblant de dormir.",
  "La rivière est fière, mais elle vient de la source.",
  "Ce n'est pas parce que la chèvre boit qu'elle est ivre.",
  "L'oiseau qui vole trop bas finit dans la marmite.",
  "Le tam-tam résonne loin, mais c'est près de lui qu'on le comprend le mieux.",
  "Quand la musique change, il faut aussi changer de danse.",
  "Un panier plein d'eau ne craint pas la pluie.",
  "Ce que les yeux n'ont pas vu, le cœur ne le regrette pas.",
  "L'éléphant ne trébuche jamais deux fois sur la même racine.",
  "Le lion ne se retourne pas pour voir les petits chiens qui aboient.",
  "On récolte ce que l'on sème.",
  "Le pagne le plus court finit toujours par se raccourcir davantage.",
  "Chaque jour a sa propre charge.",
  "Il n'y a pas de fumée sans feu.",
  "Le tambour ne bat pas de lui-même.",
  "La sagesse n'a pas d'âge.",
  "L'eau qui dort n'est pas forcément tranquille.",
  "Deux crocodiles ne vivent pas dans le même trou.",
  "On ne peut pas empêcher le vent de souffler, mais on peut orienter la voile.",
  "Le vrai courage se voit dans l'adversité.",
  "Quand le tam-tam de la vérité résonne, tout le monde danse.",
  "L'oiseau construit son nid brin par brin.",
  "Le puits ne sait pas la valeur de l'eau tant qu'il n'est pas à sec.",
  "Un vieux vêtement raccommodé vaut mieux qu'un habit neuf déchiré.",
  "La main qui donne est toujours au-dessus de celle qui reçoit.",
  "Ce n'est pas la taille du chien qui compte dans la bagarre, mais sa détermination.",
  "L'ombre du baobab protège même celui qui ne l'a pas planté.",
  "Un pauvre qui rit vaut mieux qu'un riche qui pleure.",
  "Là où il y a une volonté, il y a un chemin.",
  "Le poisson pourrit toujours par la tête.",
  "On ne juge pas la profondeur d'une rivière avec les deux pieds.",
  "Le sourire d'un enfant illumine toute une maison.",
  "L'expérience est un peigne que la vie nous donne quand nous n'avons plus de cheveux.",
  "Ce que le feu ne peut pas brûler, il le noircit au moins.",
  "Le vrai ami se reconnaît dans le malheur.",
  "Quand tu ne sais pas où tu vas, souviens-toi d'où tu viens.",
  "Une seule main ne peut pas attacher un fagot.",
  "Ce que possède le riche, le pauvre le désire ; ce que possède le pauvre, le riche l'ignore.",
  "L'hyène ne mange jamais dans un endroit qu'elle n'a pas d'abord observé.",
  "Le respect s'obtient en le donnant.",
  "Le chemin le plus long commence toujours par un premier pas.",
  "On ne peut pas empêcher les vagues, mais on peut apprendre à surfer.",
  "La vérité est comme l'huile : elle finit toujours par remonter à la surface.",
  "Il vaut mieux marcher lentement dans la bonne direction que courir dans la mauvaise.",
  "Le sage écoute avec les oreilles, pas seulement avec les yeux.",
  "Le fils du chef n'est chef que dans son village.",
  "Quand tu creuses une tombe pour ton ennemi, creuses-en deux.",
  "Ce que l'on partage se multiplie, ce que l'on garde s'épuise.",
  "Le baobab ne pousse pas dans une seule saison.",
  "La force sans la sagesse s'effondre sur elle-même.",
  "L'homme qui a soif ne se souvient plus de la couleur de l'eau.",
  "Un mensonge répété mille fois ne devient jamais une vérité.",
  "La faim ne connaît pas de calendrier.",
  "On ne coupe pas l'arbre sur lequel on est assis.",
  "Le voyageur qui ne demande pas son chemin finit par se perdre.",
  "Le tissu se déchire toujours au niveau du fil le plus faible.",
  "Le fleuve n'oublie jamais son chemin vers la mer.",
  "Ce que la sueur a construit, la paresse ne peut le détruire en un jour.",
  "L'aigle ne chasse pas les mouches.",
  "Le tam-tam ne parle qu'à celui qui sait l'écouter.",
  "Quand on est nombreux à porter le fardeau, il devient léger.",
  "La lumière d'une bougie ne diminue pas parce qu'elle en allume une autre.",
  "L'arbre tombé se voit de loin, l'arbre debout on l'oublie.",
  "On ne peut pas cacher la fumée d'un feu qu'on vient d'allumer.",
  "Le vrai trésor d'un homme, c'est sa parole donnée.",
  "Celui qui sait pardonner s'ouvre les portes de la paix.",
  "Le crapaud ne court pas en plein jour sans raison.",
  "La graine ne connaît pas la hauteur de l'arbre qu'elle deviendra.",
  "L'esclave d'aujourd'hui peut être le maître de demain, et inversement.",
  "Le silence d'un sage vaut plus que les paroles d'un fou.",
  "On ne construit pas une maison en un jour.",
  "Le vieux fromager ne tremble pas au premier vent.",
  "La rivière qui a de l'eau ne fait pas de bruit.",
  "L'oiseau chante non parce qu'il a une réponse, mais parce qu'il a un chant.",
  "Ce n'est pas le nombre d'années qui rend un homme sage, mais ses expériences.",
  "On ne montre pas ses dents à celui qui vous a mordu.",
  "Le fils du léopard est aussi tacheté que son père.",
  "L'eau et l'huile ne se mélangent jamais, comme la vérité et le mensonge.",
  "Quand le sommet de la termitière est franchi, on ne redescend plus.",
  "La chèvre broute là où elle est attachée, mais elle rêve d'ailleurs.",
  "Le pauvre n'a pas de petit frère.",
  "Un homme sans but est comme un bateau sans gouvernail.",
  "L'écorce protège l'arbre, la sagesse protège l'homme.",
  "On reconnaît le bon cultivateur à la récolte.",
  "Le tam-tam annonce la fête, mais c'est la danse qui la fait vivre.",
  "Il n'y a pas de petit ennemi.",
  "Ce que l'on sème dans la jeunesse, on le récolte dans la vieillesse.",
  "L'ombre suit le corps sans jamais le devancer.",
  "Le vent porte les paroles légères, mais pas les actes.",
  "On ne peut pas empêcher un homme déterminé de trouver un chemin.",
  "La vérité ne craint pas l'enquête.",
  "Le lièvre rusé creuse toujours plus d'un terrier.",
  "Ce que l'on n'a pas semé, on ne peut pas le récolter.",
  "L'arc-en-ciel n'apparaît qu'après la pluie.",
  "Le respect des anciens est la richesse des jeunes.",
  "Le doigt qui montre la lune n'est pas la lune.",
  "On ne devient pas riche sans se lever tôt.",
  "Le miel attire, mais c'est l'abeille qui pique.",
  "Il faut voir la termitière pour comprendre le travail des termites.",
  "Ce n'est pas la longueur du discours qui compte, mais sa vérité.",
  "L'enfant qui n'est pas embrassé par son village finira par l'incendier pour en sentir la chaleur.",
  "Le fleuve profond coule sans bruit.",
  "La patience fait bouillir la pierre et en fait sortir l'eau.",
  "On mesure la grandeur d'un homme à sa manière de traiter les plus petits que lui.",
  "Le meilleur moment pour planter un arbre était il y a vingt ans ; le second meilleur moment, c'est maintenant.",
  "L'orgueil précède toujours la chute.",
  "Ce que possède la fourmi, elle le partage avec sa colonie.",
  "Le vrai chasseur ne compte pas les flèches perdues, mais le gibier ramené.",
  "On ne peut pas voir son propre dos sans un miroir.",
  "La colère est un feu qui brûle d'abord celui qui la porte.",
  "Le baobab qu'on ne peut abattre en un jour, on l'entaille chaque jour.",
  "L'homme qui a construit sa maison ne craint pas la pluie.",
  "Le silence est parfois la réponse la plus forte.",
  "On ne peut nourrir tout le village avec un seul grain de mil, mais chaque grain compte.",
  "La rosée du matin ne dure pas jusqu'à midi.",
  "Ce n'est pas parce qu'un homme est petit qu'il ne peut pas porter une grande charge.",
  "Le tambour qui résonne trop fort finit par se déchirer.",
  "L'homme sage construit son toit avant l'arrivée de la saison des pluies.",
  "On reconnaît un vrai roi à la façon dont il traite un mendiant.",
  "La flèche tirée ne revient jamais dans le carquois.",
  "Le fleuve qui refuse la pluie finit par s'assécher.",
  "Ce que l'on donne avec le cœur revient toujours multiplié.",
  "L'arbre qui plie sous le vent ne se casse pas.",
  "La bonne récolte commence par une bonne semence.",
  "On ne peut pas éteindre le soleil en fermant les yeux.",
  "Le vieux sage sait qu'il ne sait pas tout.",
  "L'unité d'un peuple se mesure à sa capacité à porter ensemble ses fardeaux.",
  "Un petit ruisseau peut devenir un grand fleuve.",
  "Le courage n'est pas l'absence de peur, mais la victoire sur elle.",
  "Ce n'est pas celui qui parle le plus fort qui a toujours raison.",
  "On ne connaît la valeur de l'ombre qu'en plein soleil.",
  "Le mil que l'on partage nourrit mieux que celui que l'on cache.",
  "La sagesse d'un peuple se trouve dans ses proverbes.",
  "Le tisserand ne se presse jamais, mais chaque fil trouve sa place.",
  "On ne peut pas être à la fois le vent et l'arbre.",
  "L'homme honnête dort tranquille même sur une natte usée.",
  "Le chien qui suit deux pistes n'en attrape aucune.",
  "Ce qui est tissé avec patience résiste au temps.",
  "La lune éclaire même le chemin qu'elle ne connaît pas.",
  "On ne peut pas apprendre à nager sans entrer dans l'eau.",
  "Le vrai richesse d'un homme se mesure à ses amis, non à ses biens.",
  "L'arbre le plus haut a commencé comme une simple graine.",
  "Le crabe apprend à marcher droit en regardant sa mère.",
  "Ce n'est pas la pluie qui mouille, mais l'endroit où l'on se tient.",
  "On ne peut pas juger la beauté d'un tissu avant qu'il ne soit terminé.",
  "Le calme précède souvent la tempête, mais aussi parfois la paix.",
  "L'esprit qui apprend chaque jour ne vieillit jamais vraiment.",
  "Le forgeron qui a peur du feu ne façonne jamais le fer.",
  "Ce que l'on construit ensemble dure plus longtemps que ce que l'on bâtit seul.",
  "La rivière n'a pas besoin de crier pour se faire entendre.",
  "On respecte l'arbre pour ses fruits, pas pour ses feuilles.",
  "Le vent le plus violent ne dure jamais toute une saison.",
  "L'homme qui écoute les conseils des anciens ne trébuche pas deux fois.",
  "Ce que le cœur ignore, les yeux ne peuvent le trouver.",
  "On sème dans la sueur, on récolte dans la joie.",
  "Le silence de la nuit prépare les paroles du jour.",
  "La confiance se construit en gouttes et se perd en torrents.",
  "L'oiseau migrateur ne oublie jamais le chemin du retour.",
  "Ce que l'on refuse de voir aujourd'hui, on devra l'affronter demain.",
  "On ne peut pas remplir un panier percé.",
  "Le vrai guerrier protège aussi ceux qui ne peuvent se défendre.",
  "La sagesse écoute avant de juger.",
  "L'arbre généreux attire plus d'oiseaux que l'arbre égoïste.",
  "Ce que l'on apprend jeune reste gravé pour toujours.",
  "On ne peut construire un pont sans connaître les deux rives.",
  "Le vrai chef marche derrière son peuple pour mieux le guider.",
  "La patience transforme la feuille de mûrier en soie.",
  "L'eau calme creuse la pierre la plus dure.",
  "Ce n'est pas la hauteur de la montagne qui compte, mais la volonté de la gravir.",
  "On récolte la moisson que l'on a semée avec amour.",
  "Le tambour du village bat pour tous, pas pour un seul homme.",
  "La vraie richesse ne s'emporte pas dans la tombe, mais dans les cœurs.",
  "L'arbre qui donne de l'ombre ne demande rien en retour.",
  "Ce que l'on construit dans l'honnêteté résiste à toutes les tempêtes.",
  "On ne peut pas allumer le feu de l'amitié avec de l'eau de méfiance.",
  "Le vent qui déracine le grand arbre ne fait que caresser l'herbe.",
  "La sagesse d'aujourd'hui est le fruit des erreurs d'hier.",
  "L'homme qui creuse un puits pour son voisin y boira aussi un jour.",
  "Ce que l'on récolte en hâte pourrit vite dans le grenier.",
  "On ne peut pas cacher le soleil derrière un seul doigt.",
  "Le vrai ami tient la lampe même dans l'obscurité la plus profonde.",
  "La patience du pêcheur remplit toujours son filet.",
  "L'arbre sans racines profondes tombe au premier vent.",
  "Ce que le cœur donne librement vaut plus que l'or.",
  "On reconnaît la force d'une corde à son fil le plus fragile.",
  "Le vrai voyage commence dans le cœur avant de commencer sur la route.",
  "La sagesse ne s'achète pas, elle se cultive.",
  "L'oiseau qui a été brûlé par le feu craint même la fumée.",
  "Ce que l'on construit avec patience ne s'effondre pas facilement.",
  "On ne mesure pas un homme à sa richesse, mais à sa parole.",
  "Le vrai courage se cache souvent dans le silence, pas dans les cris.",
];

// Fusionne les proverbes locaux avec ceux ajoutés en base par le fournisseur
async function loadAllProverbs() {
  let combined = [...PROVERBS_LOCAL];
  try {
    if (window.db) {
      const snap = await window.db.collection("proverbes").get();
      snap.forEach((doc) => {
        const data = doc.data();
        if (data && data.texte) combined.push(data.texte);
      });
    }
  } catch (e) {
    console.warn("Impossible de charger les proverbes Firestore, utilisation de la liste locale.", e);
  }
  return combined;
}

function getRandomProverb(list) {
  const source = list && list.length ? list : PROVERBS_LOCAL;
  return source[Math.floor(Math.random() * source.length)];
}

window.PROVERBS_LOCAL = PROVERBS_LOCAL;
window.loadAllProverbs = loadAllProverbs;
window.getRandomProverb = getRandomProverb;